---
- name: Change hostname of EC2 instance
  hosts: ec2
  become: true
  vars:
    new_hostname: vaultwarden

  tasks:
    - name: Set the hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: Update /etc/hosts with new hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ new_hostname }}"
        state: present
